### ISSUE TITLE
1.6版bug,无法添加新书架

### ISSUE THREAD

**Issue by blog2i2j** [smartjinyu/MyBookshelf#13]
1.6版在添加书籍界面, 点击添加新书架不会弹出输入框. 无法添加新书架.
miui系统, android 6

**Comment by smartjinyu** [comment]
感谢反馈，可以复现。接下来几天我会发布一个更新解决此 bug。
临时的解决方法是在主界面选中该书籍，从右上角的菜单中选择移动，此处可以添加新书架。

**Comment by blog2i2j** [comment]
非常感谢.
