### ISSUE TITLE
Release 1.4 lacks APK

### ISSUE THREAD

**Issue by IzzySoft** [smartjinyu/MyBookshelf#4]
Could it be you forgot to attach the `.apk` to the latest release? Could you please fill that gap? Thanks in advance!

**Comment by smartjinyu** [comment]
Sorry for my carelessness. Add it back now. Thanks for your reminder!

**Comment by IzzySoft** [comment]
Thanks a lot!

**Comment by IzzySoft** [comment]
Apologies for complaining again, but didn't you forget to increase versionName at tag v1.51? App still identifies as

    package: name='com.smartjinyu.mybookshelf' versionCode='10' versionName='1.5' compileSdkVersion='28' compileSdkVersionCodename='9'

Users will always wonder why they don't get the latest version though it's there :rofl:

**Comment by smartjinyu** [comment]
Since this is a small bug fix update, I didn't increase versionName intentionally when updating the source code and releasing it to Google Play & other app markets. However, since tag v1.5 is already used before, I have to use another tag (v1.51) on GitHub Release page. Sorry for causing confusion.

**Comment by IzzySoft** [comment]
Ah, OK – thought you might just have missed it. As long as this doesn't happen to subsequent versions as well… :rofl:

Maybe you should consider using [semantic versioning](https://semver.org/), then this would have been "1.5.1" and clear that's just a minor fix :wink:

Thanks for answering that fast – and for clarification!

**Comment by smartjinyu** [comment]
Thanks for letting me know this issue. I will definitely consider using a more consistent version rule, and avoid such case in future release.

**Comment by IzzySoft** [comment]
Cool, thanks!
