### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by debpedrano** [smartjinyu/MyBookshelf#6]
Hello there Project Owner, is there any chance I can update the logo or make some a little bit of changes. Or maybe if you have a desired one, pls tell me. and by the way, I am a graphics designer in the Philippines. Thanks !

**Comment by debpedrano** [comment]
Good day, can I update this issue?

**Comment by smartjinyu** [comment]
Thanks for your help, but currently we don't have a plan to change our logo.
