### ISSUE TITLE
能否增加一个扫描二维码添加图书信息的功能？

### ISSUE THREAD

**Issue by valuex** [smartjinyu/MyBookshelf#7]
现在v1.5版主要是通过在豆瓣或openlibrary中查询ISBN获取图书信息的，这两个网站的书籍总归是有限的，特别是很多的专业书籍和英文书籍是查不到的
希望能够增加一个扫描二维码添加书籍信息的功能，即二维码中包含有关键字段定义，形如：
[T]Title
[A]Authors
[P]Publisher
...
这样就能快速的借助一些脚本实现二维码生成，进而快速添加书籍信息。
谢谢。

**Comment by smartjinyu** [comment]
两个网站的书籍覆盖不全面（尤其是专业书籍、外文书籍）确实是个一直困扰的问题。
这种二维码是否有一个通行的定义方式？如果是一种私有的格式的话，个人感觉使用率不会很高？
另外，此软件的初衷是管理实体书架上的书籍，为少量无法自动识别的书籍提供了手动添加的功能。如果需要用到脚本批量导入的话，可能别的软件更为合适？（或者直接修改参考源码修改 db

**Comment by valuex** [comment]
谢谢回复。
我的想法是，可以通过二维码+生成二维码的工具实现高效扫码添加。
比如通过开发chrome扩展，实现自动感知amazon, springer等网站，这样就能快速实现书籍信息添加了。这样可能比通过网站api查询ISBN更为通用些。毕竟api较难获取，而解析当前网页页面，生成书籍二维码，是相对很可行的。

关于二维码的字段的通用性，这个可以参考BibTex 或者RIS。

**Comment by smartjinyu** [comment]
好像大多数网站提供的 BibTex 或 EndNote 等是以纯文本或 json 格式而非 QR code 提供？
如果有使用 Chrome 扩展 parse 网页等方式生成 QR code 再使用 BookShelf 扫码添加书籍的需求，可能用一些 PC/Web 端的专业软件来管理更加合适？本软件的设计初衷，是一个管理个人实体书籍的简单应用，这样的功能个人认为偏离了最初的设想，一般用户的需求也不会很大，如果真有需要还是建议自行 fork 后修改代码吧。
