### ISSUE TITLE
备份/导出失败

### ISSUE THREAD

**Issue by davidcelery** [smartjinyu/MyBookshelf#8]
开发者您好！我现在遇到一个问题：
我在设置里想要更改备份的位置，改到SD卡。改完后，发现一直导出/备份失败。现在想改回内部储存，却发现一直往上之后就到了根目录...，然后就再也无法选择了。

**Comment by smartjinyu** [comment]
Please provide your phone brand, OS version and app version.

**Comment by davidcelery** [comment]
> Please provide your phone brand, OS version and app version.

My phone barnd is Moto XT1635-03, Android 8.0. app version is 1.5, installed from google play.

**Comment by davidcelery** [comment]
this issue has been fixed in the new version (2020.10.19),many thanks! I have no longer use this phone but keep this app and data to wait, finally a miracle comes!

**Comment by smartjinyu** [comment]
Glad it works!
