### ISSUE TITLE
两点建议|Two pieces of advice

### ISSUE THREAD

**Issue by dyxang** [smartjinyu/MyBookshelf#9]
- 在 readme 增加[酷安下载地址](https://coolapk.com/apk/com.smartjinyu.mybookshelf)

- 增加 Webdav 备份功能

如能实现功能，感谢开发者：）

- Add Kuan Download address at readme

- added Webdav backup function

If so, thanks to the developers:)

> From Google translate

**Comment by smartjinyu** [comment]
感谢您的建议。

1. 目前主要的分发渠道是 Google Play，国内应用市场可能没有太多精力及时维护更新。如果访问不畅，GitHub Release 也提供了各个版本的 APK 下载。

2. 下一版本会支持 Android Documents UI 来选择备份路径，届时应可选择备份到 Webdav 等外部路径 。
